// static data for testing
// id is required as MUI rules
// on API call, based on data format recieved of response, object format will be updated based on keys names of api response
export const rowsTest = [
  {
    id: 1,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 2,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "uncompleted",
    sales: "24500 ",
  },
  {
    id: 3,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 4,
    name: "John Deo4",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 5,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 6,
    name: "John Deo6",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 7,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 8,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 9,
    name: "John Deo9",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 10,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 11,
    name: "John Deo11",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
  {
    id: 12,
    name: "John Deo",
    email: "khaled@gmail.com",
    courses: "14 Courses",
    articles: "13 Articles",
    subscribers: "312 Subscribers",
    status: "completed",
    sales: "24500 ",
  },
];
